### ISSUE TITLE
issue #1

### ISSUE THREAD

**Issue by atherdon** [roshan-auto/loopback#14]
```http://localhost:3000/api/campgrounds?filter[where][name][like]=KOA```
gives me a working well result.
I also tested relations - it works also as should be. all is good - you're did well :)

But i put it on my browser url, not call from exprlorer.
At explorer you should use a semantics of queries at loopback. so ```[where][name][like]=KOA``` wouldn't work as you expected. instead, you should use something like this ```{"where":{"name":{"like":"KOA"}}}```
not sure if this particular sample will work, but i think you got my point

**Comment by atherdon** [comment]
@roshan2008web check this

**Comment by roshan2008web** [comment]
Thanks @atherdon . 
I could get the results in both ways

![image](https://user-images.githubusercontent.com/24932665/40760659-d51ec232-64eb-11e8-94d0-f426f05e0566.png)

![image](https://user-images.githubusercontent.com/24932665/40760665-e11c8cc2-64eb-11e8-92b4-017a2ff6bfea.png)
